# Generated by Django 3.2.4 on 2021-08-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wortweise', '0002_auto_20210805_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='message',
        ),
    ]
